plt.scatter(df['Annual_Income'], df['Spending_Score'], c=df['Cluster'],cmap='rainbow')
plt.title('kMeans Clustering Annual_Income Vs Spending_Score')
plt.xlabel('Annual_Income')
plt.ylabel('Spending_Score')
plt.show()